version: '2'
services:
  application:
    image: centos:7
    volumes:
      - ./app_web:/var/www/html/app_web
    tty: true

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - data_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: mysql

  php:
    build: ./php
    ports:
      - "9000:9000"
    volumes_from:
      - application
    volumes:
      - ./php/php-fpm.d:/etc/php-fpm.d
    links:
      - mysql
    container_name: php

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/nginx_conf:/etc/nginx/
    container_name: nginx

volumes:
  data_volume: